<wsdl:definitions name="upload" targetNamespace="http://xmlns.oracle.com/ServiceBusApplication/RaveUI/upload" xmlns:tns="http://xmlns.oracle.com/ServiceBusApplication/RaveUI/upload" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="upload">
        <plnk:role name="uploadProvider" portType="tns:upload_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:include schemaLocation="nxsd_schema1.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Rest_EmptyMessage"/>
    <wsdl:message name="upload_outputMessage">
        <wsdl:part name="reply" element="html"/>
    </wsdl:message>
    <wsdl:portType name="upload_ptt">
        <wsdl:operation name="upload">
            <wsdl:input message="tns:Rest_EmptyMessage"/>
            <wsdl:output message="tns:upload_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="upload_ptt-binding" type="tns:upload_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="upload">
            <soap:operation soapAction="upload"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>